- hosts: all
  gather_facts: no
  remote_user: odroid
  #become: yes
  tasks:
  - name: "copyfile"
    copy:
     src: /home/odroid/sorting_framework/variantcall
     dest: /genomics/sorting_framework/dedupli
     #owner: root
     #group: root
     mode: 0755

